version: '3.8'

services:

  emailtodb:
    restart: on-failure
    build:
      context: ./
    ports:
      - "9091:9091"
    volumes:
      - ./:/usr/src/myapp
    networks:
      - custom_network
    environment:
      - dbHost=${DB_HOST}
      - dbUser=${DB_USER}
      - dbPassword=${DB_PASSWORD}
      - dbPort=${DB_PORT}
      - dbName=${DB_NAME}
      - dbType=${DB_TYPE}
      - emailFilter=${EMAIL_FILTER}
      - emailUser=${EMAIL_USER}
      - emailSummaryCC=${EMAIL_SUMMARY_CC}
      - emailSummaryTo=${EMAIL_SUMMARY_TO}
      - azureStorageConnectionString=${azure-storage-connection-string}
      - azureStorageContainerName=${azure-storage-container-name}
      - serviceSecrets=${serviceSecrets}
      - emailBodyRegexFilter=${emailBodyRegexFilter}
      - emailBodyEliminatorStringsSet=${emailBodyEliminatorStringsSet}
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword1
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - custom_network
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        sleep 30
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrongPassword1 -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'newDB') CREATE DATABASE newDB"
        wait
    ports:
      - "1433:1433"

volumes:
  mssql-data:

networks:
  custom_network:
    driver: bridge