version: '3.8'

services:

  emailtodb:
    restart: on-failure
    build:
      context: ./
    ports:
      - "9091:9091"
    volumes:
      - ./:/usr/src/myapp
    networks:
      - custom_network
    environment:
      - dbHost=${DB_HOST}
      - dbUser=${DB_USER}
      - dbPassword=${DB_PASSWORD}
      - dbPort=${DB_PORT}
      - dbName=${DB_NAME}
      - dbType=${DB_TYPE}
      - emailFilter=${EMAIL_FILTER}
      - emailUser=${EMAIL_USER}
      - emailSummaryCC=${EMAIL_SUMMARY_CC}
      - emailSummaryTo=${EMAIL_SUMMARY_TO}
      - azureStorageConnectionString=${AZURE_STORAGE_CONNECTION_STRING}
      - azureStorageContainerName=${AZURE_STORAGE_CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

networks:
  custom_network:
    driver: bridge