apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailtodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emailtodb
  template:
    metadata:
      labels:
        app: emailtodb
    spec:
      containers:
      - name: emailtodb
        image: emailtodb:latest
        ports:
        - containerPort: 9091
        env:
        - name: dbHost
          value: ${DB_HOST}
        - name: dbUser
          value: ${DB_USER}
        - name: dbPassword
          value: ${DB_PASSWORD}
        - name: dbPort
          value: ${DB_PORT}
        - name: emailFilter
          value: ${EMAIL_FILTER}
        - name: emailUser
          value: ${EMAIL_USER}
        - name: emailSummaryCC
          value: ${EMAIL_SUMMARY_CC}
        - name: emailSummaryTo
          value: ${EMAIL_SUMMARY_TO}